### ISSUE TITLE
Dejo de funcionar

### ISSUE THREAD

**Issue by davidwells77** [estemendoza/service.subtitles.argenteam#6]
Buenas.
Hace un tiempo que no usaba kodi pero hace unos dias cuando volvi a usarlo note que no puedo descargar mas subtitulos de argenteam. En este momento no puedo pegarte el log de mi equipo pero te dejo uno que encontre en la web que estoy casi seguro que es igual a lo que vi en el mio. Muchas gracias!
19:13:06.497 T:139768520906496   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected string or buffer
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.subtitles.argenteam/service.py", line 342, in <module>
                                                search(item)
                                              File "/storage/.kodi/addons/service.subtitles.argenteam/service.py", line 220, in search
                                                search_argenteam_api(search_string)
                                              File "/storage/.kodi/addons/service.subtitles.argenteam/service.py", line 190, in search_argenteam_api
                                                response = json.loads(content)
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                            TypeError: expected string or buffer
                                            -->End of Python script error report<--

**Comment by estemendoza** [comment]
Hola, gracias por el mensaje.

Ya subi el fix que un usuario hizo para ese problema.

Saludos
